apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-50"
  name: liferay-aws-platform-infrastructure.aws.liferay.com
spec:
  compositeTypeRef:
    apiVersion: aws.liferay.com/v1alpha1
    kind: LiferayDependencies
  mode: Pipeline
  pipeline:
    - step: liferay-infrastructure
      functionRef:
        name: function-go-templating
      input:
        apiVersion: template.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            {{`
            {{- $accountId := `}}{{ .Values.aws.accountId | quote }}{{` -}}
            {{- $liferayServiceAccountRoleName := `}}{{ .Values.liferayServiceAccountRoleName | quote }}{{` -}}
            {{- $nodesSecurityGroupId := `}}{{ .Values.aws.nodesSecurityGroupId | quote }}{{` -}}
            {{- $vpcId := `}}{{ .Values.aws.vpcId | quote }}{{` -}}
            {{- $privateSubnetIds := `}}{{ .Values.aws.privateSubnetIds | quote }}{{` -}}

            {{- $privateSubnetIdsList := $privateSubnetIds | fromJson -}}
            {{- $xr := .observed.composite.resource -}}

            {{- $databaseSpec := $xr.spec.database }}
            {{- $databaseSlots := dict "blue" $databaseSpec.blue "green" $databaseSpec.green -}}
            `}}
    - step: managed-service-details-secret
      functionRef:
        name: function-go-templating
      input:
        apiVersion: template.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            {{`
            {{- $xr := .observed.composite.resource -}}
            {{- $databaseResourceName := printf "database-%s" $xr.spec.database.activeSlot -}}
            {{- $searchResourceName := "search" -}}
            {{- $storageResourceName := printf "storage-%s" $xr.spec.storage.activeSlot -}}

            {{- $database := dict -}}
            {{- $search := dict -}}
            {{- $storage := dict -}}

            {{- if .observed.resources -}}
              {{- $database = index .observed.resources $databaseResourceName -}}
              {{- $search = index .observed.resources $searchResourceName -}}
              {{- $storage = index .observed.resources $storageResourceName -}}
            {{- end -}}

            {{- $databaseAddress := "" -}}
            {{- if kindIs "map" $database -}}
              {{- with $database }}
                {{- with .resource }}
                  {{- with .status }}
                    {{- with .atProvider }}
                      {{- $databaseAddress = .address -}}
                    {{- end -}}
                  {{- end -}}
                {{- end -}}
              {{- end -}}
            {{- end -}}

            {{- $searchEndpoint := "" -}}
            {{- if kindIs "map" $search -}}
              {{- with $search }}
                {{- with .resource }}
                  {{- with .status }}
                    {{- with .atProvider }}
                      {{- $searchEndpoint = .endpoint -}}
                    {{- end -}}
                  {{- end -}}
                {{- end -}}
              {{- end -}}
            {{- end -}}

            {{- $storageName := "" -}}
            {{- if kindIs "map" $storage -}}
              {{- with $storage }}
                {{- with .resource }}
                  {{- with .metadata }}
                    {{- with .annotations }}
                      {{- $storageName = index . "crossplane.io/external-name" -}}
                    {{- end -}}
                  {{- end -}}
                {{- end -}}
              {{- end -}}
            {{- end -}}

            {{- if and $database.connectionDetails $databaseAddress $searchEndpoint $storageName }}
            ---
            apiVersion: kubernetes.m.crossplane.io/v1alpha1
            kind: Object
            metadata:
              annotations:
                crossplane.io/external-name: {{ $xr.metadata.name }}-managed-service-details-secret
                gotemplating.fn.crossplane.io/composition-resource-name: managed-service-details-secret
              labels:
                app: liferay
                component: managed-service-details-secret
              name: {{ $xr.metadata.name }}-managed-service-details-secret
              namespace: {{ $xr.metadata.namespace }}
            spec:
              forProvider:
                manifest:
                  apiVersion: v1
                  kind: Secret
                  metadata:
                    name: managed-service-details
                    namespace: {{ $xr.metadata.namespace }}
                  type: Opaque
                  stringData:
                    DATABASE_ENDPOINT: {{ $databaseAddress | toString }}
                    DATABASE_PASSWORD: {{ $database.connectionDetails.password | default "" | toString }}
                    DATABASE_PORT: {{ $database.resource.status.atProvider.port | default 5432 | toString }}
                    DATABASE_USERNAME: {{ $database.resource.spec.forProvider.username | toString }}
                    OPENSEARCH_ENDPOINT: "https://{{ $searchEndpoint }}"
                    OPENSEARCH_PASSWORD: {{ $search.connectionDetails.password | default "" | toString }}
                    OPENSEARCH_USERNAME: {{ $search.resource.spec.username }}
                    S3_BUCKET_ID: {{ $storageName | toString }}
                    S3_BUCKET_REGION: {{ $storage.resource.spec.forProvider.region | toString }}
            {{- end }}
            `}}
    - step: apply-default-tags
      functionRef:
        name: function-tag-manager
      input:
        addTags:
          - tags:
              DeploymentName: {{ .Values.deploymentName }}
            type: FromValue
        apiVersion: tag-manager.fn.crossplane.io/v1beta1
        kind: ManagedTags
    - step: auto-detect-ready-composed-resources
      functionRef:
        name: function-auto-ready