apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.platformSyncWave | default "-20" | quote }}
  name: liferay-aws-infrastructure.aws.liferay.com
spec:
  compositeTypeRef:
    apiVersion: aws.liferay.com/v1alpha1
    kind: XLiferayDependencies

  resources:
    # --- BLUE S3 BUCKET (Doclib) ---
    - name: s3-blue
      base:
        apiVersion: s3.aws.upbound.io/v1beta1
        kind: Bucket
        spec:
          forProvider:
            region: us-west-2 # Overridden by patch
            versioningConfiguration:
              - status: Enabled # Best practice for backup/restore
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.deletionPolicy
          toFieldPath: spec.deletionPolicy
        - type: FromCompositeFieldPath
          fromFieldPath: spec.blue.storage.region
          toFieldPath: spec.forProvider.region
        - type: ToCompositeFieldPath
          fromFieldPath: metadata.annotations[crossplane.io/external-name]
          toFieldPath: status.blue.s3BucketId

    # --- GREEN S3 BUCKET (Doclib) ---
    - name: s3-green
      base:
        apiVersion: s3.aws.upbound.io/v1beta1
        kind: Bucket
        spec:
          forProvider:
            region: us-west-2
            versioningConfiguration:
              - status: Enabled
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.deletionPolicy
          toFieldPath: spec.deletionPolicy
        - type: FromCompositeFieldPath
          fromFieldPath: spec.green.storage.region
          toFieldPath: spec.forProvider.region
        - type: ToCompositeFieldPath
          fromFieldPath: metadata.annotations[crossplane.io/external-name]
          toFieldPath: status.green.s3BucketId

    # --- BLUE RDS INSTANCE ---
    - name: rds-blue
      base:
        apiVersion: database.aws.upbound.io/v1beta1
        kind: Instance
        spec:
          forProvider:
            engine: postgres
            engineVersion: "15.4"
            skipFinalSnapshot: false
          writeConnectionSecretToRef:
            namespace: crossplane-system
            name: rds-blue-credentials
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.deletionPolicy
          toFieldPath: spec.deletionPolicy
        - type: FromCompositeFieldPath
          fromFieldPath: spec.blue.database.region
          toFieldPath: spec.forProvider.region
        - type: FromCompositeFieldPath
          fromFieldPath: spec.blue.database.masterUsername
          toFieldPath: spec.forProvider.masterUsername
        - type: FromCompositeFieldPath
          fromFieldPath: spec.blue.database.instanceClass
          toFieldPath: spec.forProvider.instanceType
        - type: FromCompositeFieldPath
          fromFieldPath: spec.blue.database.storageGB
          toFieldPath: spec.forProvider.allocatedStorage
        - type: FromCompositeFieldPath
          fromFieldPath: spec.restore.snapshotIdentifier
          toFieldPath: spec.forProvider.dbSnapshotIdentifier
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.address
          toFieldPath: status.blue.databaseEndpoint
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.port
          toFieldPath: status.blue.databasePort

    - name: rds-blue-password-reader
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          forProvider:
            manifest:
              apiVersion: v1
              kind: Secret
              metadata:
                name: rds-blue-credentials # Matches the RDS target
                namespace: crossplane-system
      patches:
        - type: ToCompositeFieldPath
          fromFieldPath: data.password # Captures the Base64 value from the secret
          toFieldPath: status.blue.databasePassword
 
    # --- GREEN RDS INSTANCE ---
    - name: rds-green
      base:
        apiVersion: database.aws.upbound.io/v1beta1
        kind: Instance
        spec:
          forProvider:
            engine: postgres
            engineVersion: "15.4"
            skipFinalSnapshot: false
          writeConnectionSecretToRef:
            namespace: crossplane-system
            name: rds-green-credentials
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.deletionPolicy
          toFieldPath: spec.deletionPolicy
        - type: FromCompositeFieldPath
          fromFieldPath: spec.green.database.region
          toFieldPath: spec.forProvider.region
        - type: FromCompositeFieldPath
          fromFieldPath: spec.green.database.masterUsername
          toFieldPath: spec.forProvider.masterUsername
        - type: FromCompositeFieldPath
          fromFieldPath: spec.green.database.instanceClass
          toFieldPath: spec.forProvider.instanceType
        - type: FromCompositeFieldPath
          fromFieldPath: spec.green.database.storageGB
          toFieldPath: spec.forProvider.allocatedStorage
        - type: FromCompositeFieldPath
          fromFieldPath: spec.restore.snapshotIdentifier
          toFieldPath: spec.forProvider.dbSnapshotIdentifier
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.address
          toFieldPath: status.green.databaseEndpoint
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.port
          toFieldPath: status.green.databasePort

    - name: rds-green-password-reader
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          forProvider:
            manifest:
              apiVersion: v1
              kind: Secret
              metadata:
                name: rds-green-credentials
                namespace: crossplane-system
      patches:
        - type: ToCompositeFieldPath
          fromFieldPath: data.password
          toFieldPath: status.green.databasePassword

    - name: search
      base:
        apiVersion: opensearch.aws.upbound.io/v1beta1
        kind: Domain
        spec:
          forProvider:
            engineVersion: "Elasticsearch_7.10"
          writeConnectionSecretToRef:
            namespace: crossplane-system
            name: search-conn
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.deletionPolicy
          toFieldPath: spec.deletionPolicy
        - type: FromCompositeFieldPath
          fromFieldPath: spec.search.masterUsername
          toFieldPath: spec.forProvider.advancedSecurityOptions.masterUserOptions.masterUsername
        - type: FromCompositeFieldPath
          fromFieldPath: spec.search.instanceType
          toFieldPath: spec.forProvider.clusterConfig.instanceType
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.endpoint
          toFieldPath: status.search.endpoint
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.masterUserPassword
          toFieldPath: status.search.password

    # --- THE CONSOLIDATED SECRET (managed-service-details) ---
    - name: managed-service-details-secret
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          deletionPolicy: Delete
          forProvider:
            manifest:
              apiVersion: v1
              kind: Secret
              metadata:
                name: managed-service-details
              type: Opaque
      patches:
        # DATABASE
        - type: FromCompositeFieldPath
          fromFieldPath: spec.activeSlot
          toFieldPath: spec.forProvider.manifest.stringData.DATABASE_ENDPOINT
          transforms:
            - type: match
              matchTo:
                - type: Value
                  value: blue
                  resultFieldPath: status.blue.databaseEndpoint # Reads from XR status bubbled by rds-blue
                - type: Value
                  value: green
                  resultFieldPath: status.green.databaseEndpoint # Reads from XR status bubbled by rds-green
        - type: FromCompositeFieldPath
          fromFieldPath: spec.activeSlot
          toFieldPath: spec.forProvider.manifest.data.DATABASE_PASSWORD
          transforms:
            - type: match
              matchTo:
                - type: Value
                  value: blue
                  resultFieldPath: status.blue.databasePassword
                - type: Value
                  value: green
                  resultFieldPath: status.green.databasePassword
        - type: FromCompositeFieldPath
          fromFieldPath: spec.activeSlot
          toFieldPath: spec.forProvider.manifest.stringData.DATABASE_PORT
          transforms:
            - type: match
              matchTo:
                - type: Value
                  value: blue
                  resultFieldPath: status.blue.databasePort
                - type: Value
                  value: green
                  resultFieldPath: status.green.databasePort
        - type: FromCompositeFieldPath
          fromFieldPath: spec.activeSlot
          toFieldPath: spec.forProvider.manifest.stringData.DATABASE_USERNAME
          transforms:
            - type: match
              matchTo:
                - type: Value
                  value: blue
                  resultFieldPath: spec.blue.database.masterUsername
                - type: Value
                  value: green
                  resultFieldPath: spec.green.database.masterUsername

        # S3
        - type: FromCompositeFieldPath
          fromFieldPath: spec.activeSlot
          toFieldPath: spec.forProvider.manifest.stringData.S3_BUCKET_ID
          transforms:
            - type: match
              matchTo:
                - type: Value
                  value: blue
                  resultFieldPath: status.blue.s3BucketId
                - type: Value
                  value: green
                  resultFieldPath: status.green.s3BucketId
        - type: FromCompositeFieldPath
          fromFieldPath: spec.activeSlot
          toFieldPath: spec.forProvider.manifest.stringData.S3_BUCKET_REGION
          transforms:
            - type: match
              matchTo:
                - type: Value
                  value: blue
                  resultFieldPath: spec.blue.storage.region
                - type: Value
                  value: green
                  resultFieldPath: spec.green.storage.region

        # SEARCH
        - type: FromCompositeFieldPath
          fromFieldPath: status.search.endpoint
          toFieldPath: spec.forProvider.manifest.stringData.OPENSEARCH_ENDPOINT
        - type: FromCompositeFieldPath
          fromFieldPath: status.search.password
          toFieldPath: spec.forProvider.manifest.stringData.OPENSEARCH_PASSWORD
        - type: FromCompositeFieldPath
          fromFieldPath: spec.search.masterUsername
          toFieldPath: spec.forProvider.manifest.stringData.OPENSEARCH_USERNAME